name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Go version 1.24.2
      uses: actions/setup-go@v4
      with:
        go-version: '^1.24.2'

    - name: Run test
      run: make test
